---
title: "Merge yield and soil data"
author: "ML"
date: "2023-04-25"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(tigris)
library(tidyverse)
library(lme4)
library(mgcv)
#library(itsadug)
#library(reghelper)
library(caret)
library(parallel)
library(dplyr)
library(stringr)
library(ggplot2)
library(ggpubr)
library(readr)
library(stringr)
```

# Read in data 

```{r data}

crops <- c("BARLEY",     "CORN",       "COTTON",     "OATS",       "PEANUTS",
           "SORGHUM",    "SOYBEANS",   "SUGARBEETS", "TOBACCO",     "WHEAT" )

#weather data
all_weather <- read_rds('data/all_crop_county_annual_and_mean_weather_2000_2023.rds')

```

# Merge datasets

```{r merge}
library(magrittr)
# define data path

yield_path <- 'data/nass_processed_yield/'
soil_path <- 'data/processed_soil/'
fertilizer_path <- 'data/fertilizer_data/'

output_path <- 'data/merged_data/'

# define the combine function
combine_function <- function(crop_name) {
  
  # print the progress
  cat('Start data merging for', crop_name, '......\n')

  # Yield data
  yield <- read.csv(paste0(yield_path,'nass_processed_yield',crop_name,'_yield_2000_2023_n_15.csv'))
  # Ensure the 'GEOID' column is a string with 5 characters, left-padded with zeros
  yield$GEOID <- formatC(yield$GEOID, width = 5, format = 'd' ,flag = '0')
  
  # print the number of observations from yield
  cat('Number of yield observations', nrow(yield), '\n')
  cat('Number of yield counties', length(unique(yield$GEOID)), '\n')

  #gssurgo soil data
  soil <- read_rds(paste0(soil_path,str_to_lower(crop_name),'_gssurgo.soil.stats.area_cdl_om10.rds'))
  # print the number of observations from soil
  cat('Number of soil counties', length(unique(soil$GEOID)), '\n')

  # fertilizer data
  nitrogen_file <- paste0(fertilizer_path,str_to_lower(crop_name),'_Ninput_county_mean.rds')
  if(file.exists(nitrogen_file)) {
    nitrogen <- read_rds(nitrogen_file)
  } else {
    nitrogen <- NULL
    cat('Nitrogen file not found for', crop_name, '- skipping nitrogen join.\n')
  }
  
  # weather data
  weather <- all_weather %>%
    filter(crop == crop_name)
  
  # Merge all data frames
  all_data <-yield %>% 
    inner_join(soil, by = 'GEOID') %T>% 
    #The %T>% operator allows you to perform a side effect (like printing) while passing along the data unchanged.
    { cat("After inner_join with soil: ", nrow(.), " rows\n"); . } %>%
    group_by(GEOID) %>%
    filter(!any(Yield_mg_ha == 0)) %T>% # filter out counties with no yield data
    { cat("After filtering yield==0: ", nrow(.), " rows\n"); . } %>%
    ungroup(.) %>%
    filter(cell_kept_perc90 == 'Y', #ML: remove counties with >10% cells removed due to high om
      !is.na(ssurgo_soc_filter_mean),
         ssurgo_om_filter_mean < 10, # Remove super high OM county, must be soil processing error
         ssurgo_clay_filter_mean > 1) %T>% # Remove very low clay, high sand county (PINE, MN), must be soil processing error
    { cat("After filtering soil conditions: ", nrow(.), " rows\n"); . } %>%
    distinct(.) %T>%
    { cat("After distinct(): ", nrow(.), " rows\n"); . } %>%
    dplyr::select(year,crop,GEOID,state_alpha,Mean.percent.irrigated,irrigated,Yield_decomp_add,
                  ssurgo_soc_filter_mean:ssurgo_order_filter_mode) %>%
    dplyr::rename_with(~str_remove(.,'_filter')) %>% # ML: use the filtered data and rename
    mutate(#GEOID = as.factor(GEOID),
         ssurgo_h = 10^(-1*(ssurgo_ph_mean))) %>%
    inner_join(weather, by = c('state_alpha','GEOID','crop','year')) %T>%
    { cat("After inner_join with weather: ", nrow(.), " rows\n"); . } 
  
  # join nitrogen file if the file exists
  if(!is.null(nitrogen)) {
    all_data <- all_data %>%
    left_join(nitrogen, by = 'GEOID') %>% 
    { cat("After join with nitrogen: ", nrow(.), " rows\n"); . }
  }
  
  # print the number of final counties 
  cat('---------Final results for:',crop_name,'-----------\n')
  cat('Number of final observations:', nrow(all_data),'\n')
  cat('Number of final counties:', length(unique(all_data$GEOID)), '\n')
  cat('Number of final states:', length(unique(all_data$state_alpha)), '\n')
  cat('------Process done for:',crop_name,'------------\n')

  saveRDS(all_data, paste0(output_path, crop_name,"_all_data_soil_weather_N_n15_om10_AFT.rds"))

}

# apply the function to all crops

lapply(crops, combine_function)


```

Extract county crop list
```{r county_list}
#### Extract an all-county list ####

# Define the folder containing the rds files
folder_path <- "data/merged_data/"

# Get a list of all CSV files in the folder
rds_files <- list.files(path = folder_path, pattern = "*.rds", full.names = TRUE)

# Create a container to store data from each file
lst <- list()

# Loop through each CSV file
for (file in rds_files) {
  # Read the CSV file
  data <- read_rds(file)
  
  # Ensure the 'GEOID' column is a string with 5 characters, left-padded with zeros
  data$GEOID <- formatC(data$GEOID, width = 5, format = 'd' ,flag = '0')
  
  # Extract unique GEOID values
  crop_summary <- data %>%
    dplyr::select(crop,state_alpha,GEOID) %>%
    unique()

  # Store the result in the list
  lst[[file]] <- crop_summary
}

# Combine all the unique rows from all files
all_crop_county <- do.call(dplyr::bind_rows,lst) %>% 
  unique() 


# Transform the data into a wide format
all_crop_county_wide <- all_crop_county %>%
  # Create binary indicators for each crop
  mutate(present = 1) %>%
  pivot_wider(
    names_from = crop,      # Create one column for each crop
    values_from = present,  # Fill with the binary indicator (1 for presence)
    values_fill = 0         # Fill missing values with 0
  )

# arrange the counties by the number crops 
all_crop_county_wide_order <- all_crop_county_wide %>%
  # Create a new column with the sum of all crop columns
  mutate(crop_sum = rowSums(across(BARLEY:WHEAT))) %>%
  # Order by crop_sum (lowest to highest)
  arrange(desc(crop_sum))

write.csv(all_crop_county_wide_order, file = 'data/intermediate/all_10_crops_merged_data_county_list_ordered_2000_2023.csv',
          row.names = FALSE)


```

Extract baseline SOM

```{r SOM}

# Define the folder containing the rds files
folder_path <- "data/merged_data/"

# Get a list of all CSV files in the folder
rds_files <- list.files(path = folder_path, pattern = "*.rds", full.names = TRUE)

# Create a container to store data from each file
lst <- list()

# Loop through each CSV file
for (file in rds_files) {
  # Read the CSV file
  data <- read_rds(file)
  
  # Ensure the 'GEOID' column is a string with 5 characters, left-padded with zeros
  data$GEOID <- formatC(data$GEOID, width = 5, format = 'd' ,flag = '0')
  
  # Extract unique GEOID values
  crop_summary <- data %>%
    dplyr::select(crop,state_alpha,GEOID,ssurgo_om_mean) %>%
    unique()

  # Store the result in the list
  lst[[file]] <- crop_summary
}

# Combine all the unique rows from all files
all_crop_county <- do.call(dplyr::bind_rows,lst) %>% 
  unique() 

data(fips_codes) #ML: this is a dataset from the package tigris
fips_codes #ML: 3247 observations
fips_codes <- fips_codes %>%
  mutate(CH.GEOID = paste(state,county_code, sep = ""), 
         GEOID = paste(state_code,county_code, sep = "")) %>%
  #filter(GEOID %in% unique(nass_15$GEOID)) %>%  
  mutate(county = str_remove(county, " County")) 

SOM_1 <- all_crop_county %>% 
  left_join(fips_codes, by = 'GEOID') %>%
  dplyr::select(GEOID,ssurgo_om_mean, crop, state, state_name,county) %>%
  mutate(county = toupper(county),
         crop = str_to_title(crop)) %>%
  mutate(crop = case_when(crop == 'Sugarbeets' ~ 'Sugar Beets', TRUE ~ crop)) %>%
  rename(fipsint = GEOID, 
         base_SOM = ssurgo_om_mean,
         Crop = crop,
         State = state,
         County = county)

saveRDS(SOM_1, file='../RShiny_General_Info_Data/SOM_County_Base_Update_1.rds')

# check dataframe differences: before SOM 10% filter vs. after
# choose the join key
key_cols <- c("fipsint","Crop","State","state_name","County")

A <- SOM_1
B <- SOM_County_Base_Update

# 0) quick sizes
cat("Rows A:", nrow(A), " Rows B:", nrow(B), "\n")

# 1) Keys-only comparison (distinct by the key)
A_keys <- A %>% distinct(across(all_of(key_cols)))
B_keys <- B %>% distinct(across(all_of(key_cols)))

# these are the rows filtered out 
only_in_B_keys <- anti_join(B_keys, A_keys, by = key_cols)

saveRDS(only_in_B_keys, file = '../RShiny_General_Info_Data/Rows_removed_in_SOM_County_Base_Update_1.rds')

```

# (didn't run) explore data using ggplots 

```{r check}
#all_data <- read_rds('data/AFT-data/corn_all_data_n15_om10_AFT.rds')
all_data <- read_rds('data/AFT-data/corn_all_data_w_irrigation_n15_om10_AFT.rds')

rainfed <- all_data %>% filter(irrigated == 'rainfed')

irrigated <- all_data %>% filter(irrigated == 'irrigated')

#-----yield_SOM relationship ----####
# all data
ggplot(data = rainfed) +
  geom_point(aes(x = ssurgo_om_mean, y = Yield_decomp_add)) +
  #geom_smooth(method = 'loess') +
  #geom_smooth(method = 'lm') +
  #stat_regline_equation() #+
  labs(x = 'SOM (%)', y = 'Corn yield (Mg/ha)', title = 'Rainfed') +
  theme_bw() +
  theme(
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 16)
  )

ggplot(data = irrigated) +
  geom_point(aes(x = ssurgo_om_mean, y = Yield_decomp_add, fill = Mean.percent.irrigated), shape=21) +
  #geom_smooth(method = 'loess') +
  #geom_smooth(method = 'lm') +
  #stat_regline_equation() #+
  labs(x = 'SOM (%)', y = 'Corn yield (Mg/ha)', title = 'Irrigated') +
  theme_bw() +
  theme(
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 16)
  )

ggplot(data = all_data) +
  geom_point(aes(x = ssurgo_om_mean, y = Yield_decomp_add, group = irrigated, fill = irrigated), shape=21) +
  geom_smooth(aes(x = ssurgo_om_mean, y = Yield_decomp_add, group = irrigated, color = irrigated), method = 'loess') +
  #geom_smooth(aes(x = ssurgo_om_mean, y = Yield_decomp_add, group = irrigated, color = irrigated), method = 'lm') +
  #stat_regline_equation(aes(x = ssurgo_om_mean, y = Yield_decomp_add, group = irrigated)) +
  labs(x = 'SOM (%)', y = 'Corn yield (Mg/ha)') +
  theme_bw() +
  theme(
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 16)
  )

# by state
ggplot(data = rainfed, aes(x = ssurgo_om_mean, y = Yield_decomp_add)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  facet_wrap(~state_alpha) +
  stat_regline_equation() #+
  #scale_y_continuous(limits = c(0,17))

ggplot(data = irrigated) +
  geom_point(aes(x = ssurgo_om_mean, y = Yield_decomp_add, fill = Mean.percent.irrigated), shape = 21) +
  #geom_smooth(method = 'lm') +
  facet_wrap(~state_alpha) +
  #stat_regline_equation()
  labs(x = 'SOM (%)', y = 'Corn yield (Mg/ha)', title = 'Irrigated') +
  theme_bw()

ggplot(data = all_data) +
  geom_point(aes(x = ssurgo_om_mean, y = Yield_decomp_add, fill = Mean.percent.irrigated), shape = 21) +
  #geom_smooth(method = 'lm') +
  facet_wrap(~state_alpha) +
  #stat_regline_equation()
  labs(x = 'SOM (%)', y = 'Corn yield (Mg/ha)', title = 'All') +
  theme_bw()

#----ggplot highlight target state----#
library(gghighlight)
ggplot(data = rainfed, aes(x = ssurgo_om_mean, y = Yield_decomp_add)) +
  geom_point() +
  gghighlight(state_alpha == 'PA')
  
ggplot(data = irrigated) +
  geom_point(aes(x = ssurgo_om_mean, y = Yield_decomp_add, fill = Mean.percent.irrigated), shape = 21) +
  gghighlight(state_alpha == 'NE')

#----check OM range of each state----#

om_range <- rainfed %>%
  group_by(state_alpha) %>%
  reframe(om_range = range(ssurgo_om_mean)) %>%
  mutate(range = rep(c('min','max'),27)) 

ggplot(data = om_range, aes(x = om_range, y = state_alpha, group = state_alpha)) +
  geom_line()

yield_range <- rainfed %>%
  group_by(state_alpha) %>%
  reframe(yield_range = range(Yield_decomp_add)) %>%
  mutate(range = rep(c('min','max'),27)) 

ggplot(data = yield_range, aes(x = yield_range, y = state_alpha, group = state_alpha)) +
  geom_line()

```
